### ISSUE TITLE
New instrument nodes are not visible

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/Quince#2]
I'm not entirely sure of the steps to reproduce this. But, what I did was:
* trash my libraries (all of them)
* create an X6 and an Alazar digitizer
* launch Quince, see nothing

If I enter a debug prompt, I can discover that the scene does in fact contain two nodes with my two digitizers. However, I cannot "find" them in the view.

**Comment by caryan** [comment]
I can confirm this is reproducible.  It seems to need a stream selector for anything to show up.

**Comment by blakejohnson** [comment]
Ah, yes. If I add a stream selector before opening Quince, then the nodes appear.
