### ISSUE TITLE
Corrupt data in QSettings

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/Quince#4]
While dealing with #3, I have frequently run into a problem where the position data in QSettings gets corrupted. Consequently, I've been doing this a lot:
```python
from qtpy.QtCore import QSettings
settings = QSettings("BBN", "Quince")
settings.clear()
settings.sync()
```

It would be better to track down where this error is actually thrown and handle it more gracefully.

**Comment by grahamrow** [comment]
Which OS/Qt versions are you on right now?
https://bugreports.qt.io/browse/QTBUG-56664

**Comment by grahamrow** [comment]
Looks like there won't be any qt5.7 packages in the base packages or conda-forge for quite a while. I'll look into workarounds — brewed versions of pyqt is at 5.8.1 fwiw.

**Comment by grahamrow** [comment]
Should be addressed by 9d94507d. Leaving this open so we don't forget platform dependent issues.

**Comment by blakejohnson** [comment]
I think you have just convinced me not to update my work computer to Sierra.

**Comment by grahamrow** [comment]
{Sierra, anaconda} choose 1.

**Comment by grahamrow** [comment]
@blakejohnson suggested keeping json files with this information instead. I'm for this, since we may want the flexibility to switch between different sets of config files without obliterating previously defined node layouts.

**Comment by grahamrow** [comment]
Now using raw floats instead of `QPointF`s, which don't seem to serialize properly.
