### ISSUE TITLE
run-quince.py doesn't run on Linux

### ISSUE THREAD

**Issue by caryan** [BBN-Q/Quince#5]
Maybe on macOS there is some automagic but on Linux the shebang needs to be correct and the Python scripts needs executable permissions.

**Comment by caryan** [comment]
Since in `setup.py` we write `run-quince.bat` with an explicit `python` call do we need the shebang for Windows? Can we just make the run-quince.py Linux/Mac centric?

**Comment by grahamrow** [comment]
Since we explicitly pick the python binary on windows I think that's reasonable.

**Comment by caryan** [comment]
Should be handled by #6

**Comment by grahamrow** [comment]
Assuming this works.
