### ISSUE TITLE
Layout gets lost after saving yaml

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Quince#8]
Updating the yaml or relaunching Quince does not keep the last layout

**Comment by grahamrow** [comment]
Confirmed on MacOS, looking into it. Tremendously annoying.

**Comment by grahamrow** [comment]
So the default behavior was to save the node positions on save. If you just moved things without saving then they would revert on close or reload. I put the saving on a 3s timer and also have it save again right before reloading. If you're really fast you might be able to trick it still, but I'm not too worried.
