### ISSUE TITLE
Receiver channel must be string

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Quince#9]
QGL expects the receiver channel to be a [string](https://github.com/BBN-Q/QGL/blob/e30c6dc9d0764953929742c39761bc3986e8ce63/QGL/Channels.py#L123), but Quince saves it as an integer.

**Comment by dieris** [comment]
I guess it doesn't have to be a string... change in class `ReceiverChannel` to `channel = Int()`?

**Comment by grahamrow** [comment]
Hmm, which should acquiesce? I feel like strings for channels allow for more generality. I'll look into changing this on the Auspex side.

**Comment by grahamrow** [comment]
It was easier to just `str()` the channel in QGL. Seems fine with fake data. Let me know if it works IRL.
